### ISSUE TITLE
Features as columns is tidy IMHO

### ISSUE THREAD

**Issue by aghatpande** [stemangiola/bioc2021_tidytranscriptomics#34]
I am still following along the workshop and forked it for myself. Haven't finished it yet and so I could be mistaken in my understanding. IMHO, in single cell transcriptomics aren't features / genes the 'natural' variables that define a cell? Hence features should be columns and each cell (observation) be rows? 
I am not sure I understand the structure of either the "tidy summarized experiment" or the "tidy single cell experiment" container structure to see that they are indeed organized accordingly. Although, I do see that most dplyr / ggplot functions work well with them. Hoping you will comment and clarify. 
Thank you for the project and the workshop.

**Comment by stemangiola** [comment]
Let's think in the perspective of bulk RNA sequencing, it is easier and equivalent.  In the perspective of a linear model that is 

```
factor_of_interest ~ gene1 + gene2 + gene3

```

It makes complete sense complete sense to think about genes as features. This could be thought as tidy. As you say (feature as columns).

However transcriptomics is a bit special. Because we have so many genes such a linear model is not feasible in most cases. We have instead this one

```
Gene1 ~ factor_of_interest
Gene2 ~ factor_of_interest
```

That's why genes becomes the element and factor of interest the feature.

But let's forget about all this, because samples are a self-similar variable, and genes are self-similar as well. Therefore they become variable types (of variables full stop). That is why the representation

sample | feature (gene) | value

is very tidy, and allows to represent all data in one (non rectangular) dataframe. The visualisation comes natural, adding sample/gene information comes natural. And so on.

For single cell, we are just showing cell information by default, for the reason we explain the workshop. The representation here is more straighforward.

**Comment by aghatpande** [comment]
Nice explanation, so the cell / feature of interest become the independent variables. Thanks for this

**Comment by stemangiola** [comment]
Let's say transcriptomic data representation does not reflect any statistical mode, neither the rectangular of the tidy version. 

Glad to have helped.
